# Copyright (c) 2024-2025 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config:
  gitops:
    mtkconnect:
      router: harbor.scpmtk.com/mtk-connect/mtk-connect-router:v2.2.8
      authenticator: harbor.scpmtk.com/mtk-connect/mtk-connect-authenticator:v3.5.2
      wamprouter: harbor.scpmtk.com/mtk-connect/mtk-connect-wamprouter:v3.0.27
      devices: harbor.scpmtk.com/mtk-connect/mtk-connect-devices:v7.8.0
      portal: harbor.scpmtk.com/mtk-connect/mtk-connect-portal:v5.8.0
      installers: harbor.scpmtk.com/mtk-connect/mtk-connect-installers:v1.8.0
      docs: harbor.scpmtk.com/mtk-connect/mtk-connect-docs:v2.0.12
spec:
  destination:
    server: https://kubernetes.default.svc
