# Copyright (c) 2024-2025 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: gke-argocd-sa@##PROJECT_ID##.iam.gserviceaccount.com
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ##REPO_URL##
  type: git
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secret-store
  namespace: argocd
spec:
  provider:
    gcpsm:
      projectID: "##PROJECT_ID##"
      auth:
        workloadIdentity:
          clusterLocation: ##CLOUD_REGION##
          clusterName: sdv-cluster
          serviceAccountRef:
            name: argocd-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-creds
  namespace: argocd
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store
  target:
    name: argocd-github-creds
    creationPolicy: Merge
  data:
    - secretKey: githubAppID
      remoteRef:
        key: githubAppID
    - secretKey: githubAppInstallationID
      remoteRef:
        key: githubAppInstallationID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: githubAppPrivateKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocdInitialPassword
        decodingStrategy: Base64
